grpc_port: 50051

postgres:
  user: admin
  password: pass
  host: postgres
  port: 5432
  db_name: e-petitions-project-db

redis:
  host: redis
  port: :6379
  password: redispass
  db: 0

tokens:
  T_KEY: eyJhbGciOiJIU
  RT_KEY: tetetepolsvbJk

rabbit:
  host: rabbitmq
  port: 5672

gateway:
  host: localhost
  port: :1337
